kafka: check api_version
aiven/journalpump pull request #78
Opened 2020-10-13 10:22 UTC by gabriel-tincu

When enabling ZSTD, check the kafka api version , since the compression
algorithm requires a cluster version of 2.1.0 or higher

2020-12-02 15:23 UTC, hackaugusto commented
This is done by `kafka-python` already:

https://github.com/dpkp/kafka-python/blob/9feeb79140ed10e3a7f2036491fc07573740c231/kafka/producer/kafka.py#L395-L396

2020-12-03 10:47 UTC, ivanyu requested changes

2020-12-03 10:47 UTC, ivanyu commented on journalpump/senders/kafka.py
> +                if zstd and "zstd" in KafkaProducer._COMPRESSORS and parsed >= (2, 1, 0):
Maybe, use `LooseVersion`?

2022-06-07 08:10 UTC, fingon commented
@ivanyu is this still worth doing or should we close it?

2022-06-07 08:30 UTC, ivanyu commented
I think we don't need to care about that old Kafka versions.

2022-06-07 08:30 UTC, closed without merging